# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Marcin Przewięźlikowski
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello there! My name is Marcin and I am a PhD student @ <a href="https://gmum.net/">GMUM</a> / <a href="https://matinf.uj.edu.pl/en_GB/">Jagiellonian University</a> / <a href="https://ideas-ncbr.pl/en/research/zero-waste-machine-learning-in-computer-vision/">IDEAS NCBR</a>.
  
  I am passionate about all things Machine Learning, comics, cycling and skiing. 

  <p>
  In 2021 I received a Master's Degree in Computer Science from Jagiellonian University and in 2019, a BSc. of Engineering from AGH University of Science and Technology.
  <p>
  I am based in Cracow, Poland.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: https://mprzewie.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pszwnzl
github_username:  mprzewie
mail: "marcin.przewiezlikowski [on] doctoral.uj.edu.pl"

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
logo: /assets/img/logo.jpg

external_urls:
  github: https://github.com/mprzewie
  scholar: https://scholar.google.com/citations?hl=pl&user=yQkER-MAAAAJ
  linkedin: https://www.linkedin.com/in/marcin-przewi%C4%99%C5%BAlikowski-aa5b82135/
  shelfwise: https://shelfwise.ai
  usos: https://www.usosweb.uj.edu.pl/kontroler.php?_action=katalog2/osoby/pokazOsobe&os_id=278780
  twitter: https://twitter.com/pszwnzl



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
